"""initial schema

Revision ID: fbd9bc9e1ef8
Revises: 
Create Date: 2026-07-20 17:56:44.814391
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fbd9bc9e1ef8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_sha256'), ['sha256'], unique=False)

    op.create_table('checkpoints',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('watermark', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('run_id', 'key')
    )
    op.create_table('entities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('graph_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('canonical_key', sa.String(length=256), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_canonical_key'), ['canonical_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_graph_id'), ['graph_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_type'), ['type'], unique=False)

    op.create_table('failed_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('seed_id', sa.String(length=64), nullable=True),
    sa.Column('page_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('failed_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_failed_items_run_id'), ['run_id'], unique=False)

    op.create_table('pages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('seed_id', sa.String(length=64), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('rendered', sa.Boolean(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pages_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index('ix_pages_run_hash', ['run_id', 'content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_seed_id'), ['seed_id'], unique=False)

    op.create_table('relationships',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('graph_id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationships_graph_id'), ['graph_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_target_id'), ['target_id'], unique=False)

    op.create_table('runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('graph_id', sa.String(length=64), nullable=True),
    sa.Column('audit_log_ref', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_status'), ['status'], unique=False)

    op.create_table('seed_decisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('seed_id', sa.String(length=64), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('rule', sa.String(length=128), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seed_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seed_decisions_run_id'), ['run_id'], unique=False)

    op.create_table('seeds',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('identifiers', sa.JSON(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('parent_seed_id', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seeds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seeds_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_seeds_run_status', ['run_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_seeds_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seeds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seeds_status'))
        batch_op.drop_index('ix_seeds_run_status')
        batch_op.drop_index(batch_op.f('ix_seeds_run_id'))

    op.drop_table('seeds')
    with op.batch_alter_table('seed_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seed_decisions_run_id'))

    op.drop_table('seed_decisions')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_status'))

    op.drop_table('runs')
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationships_target_id'))
        batch_op.drop_index(batch_op.f('ix_relationships_source_id'))
        batch_op.drop_index(batch_op.f('ix_relationships_graph_id'))

    op.drop_table('relationships')
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pages_seed_id'))
        batch_op.drop_index(batch_op.f('ix_pages_run_id'))
        batch_op.drop_index('ix_pages_run_hash')
        batch_op.drop_index(batch_op.f('ix_pages_content_hash'))

    op.drop_table('pages')
    with op.batch_alter_table('failed_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_failed_items_run_id'))

    op.drop_table('failed_items')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_type'))
        batch_op.drop_index(batch_op.f('ix_entities_graph_id'))
        batch_op.drop_index(batch_op.f('ix_entities_canonical_key'))

    op.drop_table('entities')
    op.drop_table('checkpoints')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_sha256'))
        batch_op.drop_index(batch_op.f('ix_assets_run_id'))

    op.drop_table('assets')
    # ### end Alembic commands ###
